#

# NORMALIZATION

## Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling process. Centering means subtracting the data from the
mean and scaling means dividing with its standard deviation. Mathematically, normalization can be
expressed as: 𝑍 = ( 𝑋 − 𝑥̅ ) / 𝜎
In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and
.std() calls.
In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
ndarray as X_normalized.npy

In [323]:
import numpy as np
#Creates a random 5x5 ndarray and stored in the x variable. There's an additional parameter so that the random numbers produced is bounded from just 0 - 10.
x = np.random.randint(0,10,(5,5))
#The formula for normalization is stored in z variable.
#np.mean gets the mean of the ndarray x and np.std gets the standard deviation of the ndarray x
z = (x-(np.mean(x)))/np.std(x)
#the ndarray is then saved to 'normalized.npy'
np.save('normalized.npy', z) 
z

array([[-1.53235353, -1.91931149, -1.14539557,  0.78939424,  1.56331016],
       [ 0.01547832,  0.78939424,  0.40243628,  0.01547832,  0.40243628],
       [ 0.01547832,  1.1763522 ,  1.56331016,  0.01547832, -0.7584376 ],
       [-0.7584376 ,  1.56331016,  0.78939424,  0.01547832,  0.78939424],
       [ 0.01547832, -0.37147964, -1.53235353, -1.53235353, -0.37147964]])

In [325]:
#Loads the 'normalized.npy' file for verification purposes
np.load('normalized.npy')

array([[-1.53235353, -1.91931149, -1.14539557,  0.78939424,  1.56331016],
       [ 0.01547832,  0.78939424,  0.40243628,  0.01547832,  0.40243628],
       [ 0.01547832,  1.1763522 ,  1.56331016,  0.01547832, -0.7584376 ],
       [-0.7584376 ,  1.56331016,  0.78939424,  0.01547832,  0.78939424],
       [ 0.01547832, -0.37147964, -1.53235353, -1.53235353, -0.37147964]])

In [327]:
#Displays the random array contents
x

array([[1, 0, 2, 7, 9],
       [5, 7, 6, 5, 6],
       [5, 8, 9, 5, 3],
       [3, 9, 7, 5, 7],
       [5, 4, 1, 1, 4]])

# DIVISIBLE BY 3 PROBLEM: Create the following 10 x 10 ndarray.
𝐴 = [
 


1 4 ⋯
⋮ ⋮ ⋱ ⋮ ⋮
8281 8464 ⋯]9801 10000]




which are the squares of the first 100 positive integers.
From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.np

In [257]:
#Initializes two empty list to Squared and div3
Squared = []
div3=[]
#Loops through from 1-100 and squares each iteration and appends it to the "Squared" list
for y in range(1, 101):
    Squared.append(y**2)
#Stores the "Squared" list to an ndarray "q" and reshapes it to 10x10
q = np.array(Squared).reshape(10,10)

#uses the now occupied list and iterates through it
#It has a condition wherein it will only append i to div3 list if it is divisible by 3.
for i in Squared:
    if i%3 == 0:
        div3.append(i)
#saves the div3 list to "div by 3.npy"
np.save('div by 3.npy', div3)
#To show the 10x10 ndarray
q

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [263]:
#loads the div by 3.npy to verify the answers
np.load('div by 3.npy')

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [321]:
#For verification purposes
#This shows all the divisible numbers by 3 starting from 3 to 100
for p in range(3, 101, 3):
    q = p**2
    print(q)

9
36
81
144
225
324
441
576
729
900
1089
1296
1521
1764
2025
2304
2601
2916
3249
3600
3969
4356
4761
5184
5625
6084
6561
7056
7569
8100
8649
9216
9801
